### ISSUE TITLE
Separate WKT grammar and actions into different files and (sub-)modules

### ISSUE THREAD

**Issue by antononcube** [kjpye/Raku-Geo-Geometry#1]
Great work! Very useful.

Please separate the WKT grammar and actions into different files and (sub-)modules.

For example, I can use a stand-alone WKT parser in "Text::Plot"; or I can program actions that produce graphic primitives for systems like Mathematica or R.

**Comment by kjpye** [comment]
I'm working on fixing numerous problems in that area. Subject to a resolution of some issues I'm having with Rakudo at the moment that shouldn't be far off.

I'll look at separating them out. Wherever the actions end up they will need to depend on Geo::Geometry, but there's no reason why a separate set of actions would need to.

Kevin.

**Comment by kjpye** [comment]
Hi,

I think I've completed the current set of planned changes, although I still need to run a final check and preferably write some more test cases.

Do you want to check out the github repository (kjpye/Raku-Geo-Geometry) and see whether what I've done will be adequate for your needs. I've left most of the boiler-plate actions in-line, but separated out the actions which actually do the work into the Geo::Geometry::WKT::Grammar module.

The documentation is at the end of the README.md (generated from doc/Geometry.rakudoc). Is this clear enough?

I hope to release this in the next couple of days before I head into the bush (beyond electronic communications) in the middle of next week,

Kevin.

**Comment by antononcube** [comment]
Yes, the refactored WKT grammar works for me. 

For example,  I can define:

```perl6
class Mathematica-Actions {

    # Point
    method point($/) {
        make 'Point[{' ~
                $<value>[0].made.Num ~ ', ' ~
                $<value>[1].made.Num ~ '}]';
    }
    method pointz($/) {
        make 'Point[' ~
                $<value>[0].made.Num ~ ', ' ~
                $<value>[1].made.Num ~ ', ' ~
                $<value>[2].made.Num ~ ']';
    }
    method pointm($/) {
        make 'Point[{' ~
                $<value>[0].made.Num ~ ', ' ~
                $<value>[1].made.Num ~ ', ' ~
                $<value>[2].made.Num ~ '}]';
    }
    method pointzm($/) {
        make 'Point[{' ~
                $<value>[0].made.Num ~ ', ' ~
                $<value>[1].made.Num ~ ', ' ~
                $<value>[2].made.Num ~ ', ' ~
                $<value>[3].made.Num ~ '}]';
    }
}
```

And then parse-interpret into Mathematica graphics code with:

```perl6
say WKT.parse('LineString(10.01 10.3,20 20,30 50)', actions => Mathematica-Actions).made;

# Line[{{10.01, 10.3}, {20, 20}, {30, 50}}]
```

-----

I have a naming suggestion:

- I think instead of `WKT` that grammar should be named something like `Geo::WKT::Grammar` or `WellKnownText::Grammar`.
